module.exports.filters = [
  { filterName: "Trending", iconClassName: "fa-solid fa-fire" },
  { filterName: "Domes", iconClassName: " fa-solid fa-igloo" },
  { filterName: "Rooms", iconClassName: "fa-solid fa-bed" },
  { filterName: "Farms", iconClassName: "fa-solid fa-cow" },
  { filterName: "Amazing pools", iconClassName: "fa-solid fa-person-swimming" },
  { filterName: "A-frames", iconClassName: "fa-solid fa-austral-sign" },
  { filterName: "Beachfront", iconClassName: "fa-solid fa-umbrella-beach" },
  { filterName: "Creative spaces", iconClassName: "fa-solid fa-palette" },
  { filterName: "Earth homes", iconClassName: "fa-brands fa-pagelines" },
  { filterName: "Arctic", iconClassName: "fa-solid fa-snowflake" },
  {
    filterName: "Castles",
    iconClassName: "fa-brands fa-fort-awesome",
  },
  { filterName: "Bed and Breakfast", iconClassName: "fa-solid fa-mug-hot" },
  { filterName: "Camping", iconClassName: "fa-solid fa-tents" },
  { filterName: "Boats", iconClassName: "fa-solid fa-sailboat" },
  { filterName: "Houseboat", iconClassName: "fa-solid fa-ship" },
  { filterName: "Golfing", iconClassName: "fa-solid fa-golf-ball-tee" },
  { filterName: "Skiing", iconClassName: "fa-solid fa-person-skiing" },
  { filterName: "Towers", iconClassName: "fa-solid fa-tower-observation" },
  { filterName: "Camper vans", iconClassName: "fa-solid fa-caravan" },
  { filterName: "Mountains", iconClassName: "fa-solid fa-mountain-sun" },
];
